import CodeGeneratorConfigTemplateGeneratorResultFile from "./CodeGeneratorConfigTemplateGeneratorResultFile/CodeGeneratorConfigTemplateGeneratorResultFile";

export default interface CodeGeneratorConfigTemplateGeneratorResult {
    files: CodeGeneratorConfigTemplateGeneratorResultFile[];
}